# Generated by Django 4.1.7 on 2023-07-03 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='discountprice',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='sellingprice',
            field=models.IntegerField(default=0),
        ),
    ]
